# Generated by Django 5.2 on 2025-09-09 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ensayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Título', max_length=200)),
                ('materia', models.CharField(default='Materia', max_length=100)),
                ('curso', models.CharField(default='Curso', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(default=list)),
                ('puntaje', models.IntegerField(default='100')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('duracion', models.DurationField(default='0')),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.ensayo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('enunciado_img', models.ImageField(blank=True, null=True, upload_to='preguntas/')),
                ('dificultad', models.CharField(default='Sin definir', max_length=50)),
                ('correct_answer', models.CharField(default='A', max_length=1)),
                ('tipo', models.CharField(choices=[('alternativa_simple', 'Alternativa Simple'), ('desarrollo', 'Desarrollo')], max_length=50)),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='ensayos.ensayo')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='ensayos.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='ensayos.ensayo')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('correcta', models.BooleanField(default=False)),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ensayos.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.pregunta')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='ensayos.resultado')),
            ],
        ),
    ]
