# Generated by Django 5.2 on 2025-09-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('alternativa_simple', 'Alternativa Simple')], max_length=50),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='preguntas', to='ensayos.etiqueta'),
        ),
    ]
