# Generated by Django 5.2 on 2025-10-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0002_etiqueta_alter_pregunta_tipo_pregunta_etiquetas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='enunciado_img',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='explicacion_texto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='explicacion_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
